### ISSUE TITLE
Problems with Command Artifact Interaction

### ISSUE THREAD

**Issue by shatteredsky888** [coolcourd/spawn-items#1]
Seems to be an issue when Command Artifact is toggled on. Item spawns, but the command window is empty. Also breaks items naturally found in chests or spawned from the Sacrifice Artifact.

**Comment by coolcourd** [comment]
Yeah, this worked before the anniversary update.  I'll look into it.

**Comment by shatteredsky888** [comment]
So I'm thinking this may have been an issue with R2API. I just updated it with version 3.0.11 and command seems to be working again. I'll continue testing to ensure it was strictly an R2API issue.

**Comment by coolcourd** [comment]
@shatteredsky888 yeah, it seems to work fine now with no update needed. ill close this issue
